---

language: python
dist: focal
services: docker

env:
  global:
    - ROLE_NAME: awscli2
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker
      - yamllint
    update: true

install:
  - pip install --upgrade --upgrade-strategy eager -r requirements.txt

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME deekayen.$ROLE_NAME
  - cd deekayen.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
