---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts.os_family == 'Debian'

- name: Update dnf cache.
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_facts.os_family == 'RedHat'

- name: Install unzip.
  ansible.builtin.package:
    name: unzip
    state: present

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Download awscliv2 installer.
  ansible.builtin.unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_facts.architecture }}.zip"
    dest: "{{ executable_temp_dir }}"
    remote_src: true
    creates: "{{ executable_temp_dir }}/aws"
    mode: "0755"

- name: Run the installer.
  ansible.builtin.command:
    cmd: "{{ executable_temp_dir }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install

- name: Show installer output.
  ansible.builtin.debug:
    var: aws_install
    verbosity: 2
