---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update yum cache.
      ansible.builtin.dnf:
        update_cache: true
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version >= 8"

    - name: Update yum cache.
      ansible.builtin.dnf:
        update_cache: true
        use_backend: yum
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version <= 7"

    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 8640
      when: ansible_distribution == 'Debian'

    - name: Install unzip.
      package:
        name: unzip
      changed_when: false
