---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        run: pip3 install ansible-lint flake8

      - name: Lint code.
        run: ansible-lint --profile production

      - name: Lint Python tests.
        run: flake8 molecule/

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          - rockylinux10
          - amazonlinux2023
          - ubuntu2204
          - ubuntu2404
          - ubuntu2604
          - debian12
          - debian13

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        run: pip3 install ansible-core molecule molecule-plugins[docker] docker pytest-testinfra

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
